[env]
  TERM = "xterm-256color"

[window]
  option_as_alt = "Both"

[general]
  import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

[font]
  normal.family = "Hack Nerd Font Mono"
  italic.family = "Monaspace Radon"

  size = 14.0
