[env]
  TERM = "xterm-256color"

[general]
  import = ["~/.config/alacritty/themes/rose-pine-moon.toml"]

[font]
  normal.family = "Hack Nerd Font Mono"
  italic.family = "Monaspace Radon"

  size = 14.0
